export enum ActionTypes {
    LOAD_CHARACTERS = "LOAD_CHARACTERS",
    LOAD_CHARACTERS_SUCCESS = "LOAD_CHARACTERS_SUCCESS",
    LOAD_CHARACTERS_ERROR = "LOAD_CHARACTERS_ERROR",
    FILTER_CHARACTERS = "FILTER_CHARACTERS",
    FILTER_CHARACTERS_SUCCESS = "FILTER_CHARACTERS_SUCCESS",
    FILTER_CHARACTERS_ERROR = "FILTER_CHARACTERS_ERROR",
    LOAD_CHARACTER = "LOAD_CHARACTER",
    LOAD_CHARACTER_SUCCESS = "LOAD_CHARACTER_SUCCESS",
    LOAD_CHARACTER_ERROR = "LOAD_CHARACTER_ERROR",
    SET_EPISODES = "SET_EPISODES"
}